language: node_js
node_js:
  - "4.2.0"
install:
  - npm install
  - npm install -g istanbul
  - npm install -g mocha
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
